
; RAK4631 WisBlock Soil Sensor
; Platform: nordicnrf52 (Adafruit BSP als Proxy für RAK4631)
; Framework: Arduino + RadioLib (kein RUI3, da RUI3 nicht PlatformIO-kompatibel

[env:node01-panorama]
platform = nordicnrf52@9.5.0
board = wiscore_rak4631
framework = arduino
build_flags =
    -D ARDUINO_WISCORE_RAK4631
    -D USE_LFXO
    -I include
    -D NODE_ID=1
    -Wno-unused-function
monitor_speed = 115200
lib_archive = no
lib_deps =
    beegee-tokyo/SX126x-Arduino @ ^2.0.22
    4-20ma/ModbusMaster @ ^2.0.1

[env:node02-beet-sued]
platform = nordicnrf52@9.5.0
board = wiscore_rak4631
framework = arduino
build_flags =
    -D ARDUINO_WISCORE_RAK4631
    -D USE_LFXO
    -I include
    -D NODE_ID=2
    -Wno-unused-function
monitor_speed = 115200
lib_archive = no
lib_deps =
    beegee-tokyo/SX126x-Arduino @ ^2.0.22
    4-20ma/ModbusMaster @ ^2.0.1
